---
CoreConfig:           # Core configuration settings for the run.
  TC_Interations: 10  # Number of times to form and teradown the IPsec tunnel, per TC setting.
  MaxTimeS: 36000      # Maximum time to run the test in seconds.
  LocalPath: "../"      # Local path to copy the logs to.
  RemotePath: "/var/log/charon.log"   # Remote path to copy the log file from.
  WiresharkLogs: false        # Capture Wireshark logs from Carol. 
  WSRemotePath: "/var/log/"   # Remote path to copy the Wireshark logs from.
  WSLocalPath: "/"            # Local path to copy the Wireshark logs to.
  MirrorMoon: false           # Do not Mirror the Carol's TC settings to Moon.
  PrintLevel: 1               # Information Display Level for the run.
  compose_files: "./pq-strongswan_config/docker-compose.yml"  # Docker compose file location
Carol_TC_Config:
  Constraint1:
    Type: netem
    Constraint: duplicate
    Interface: eth0
    StartRange: 10
    EndRange: 100
    Units: "%"
    Steps: 5
    AddParams: ''
